options:
  charset: utf8
actAs: [Timestampable]

IntroFriend:
  columns:
    id: { type: integer(4), primary: true, autoincrement: true }
    member_id_to: { type: integer(4), notnull: true }
    member_id_from: { type: integer(4), notnull: true }
    content: { type: string, notnull: true }
  relations:
    Member: { local: member_id_to, foreign: id, onDelete: cascade }
    Member_2: { class: Member, local: member_id_from, foreign: id, onDelete: cascade }
  indexes:
    created_at:
      fields: [created_at]
    member_id_from_member_id_to:
      fields: [member_id_from, member_id_to]
    member_id_to_updated_at:
      fields: [member_id_to, updated_at]

IntroFriendUnread:
  columns:
    member_id:
      type: integer(4)
      primary: true
      notnull: true
    read_at:
      type: timestamp
      notnull: true
    count:
      type: integer(4)
      notnull: true
      default: 0
      unsigned: true
  relations:
    Member:
      foreignType: one
      onDelete: cascade
      owningSide: true
